apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  {{- if not .Values.hpaBench.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        parrot-app-version: {{ .Values.appVersion }}
      annotations:
        checksum/nginx-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      containers:
      - name: parrot-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.nginx.port }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
            ephemeral-storage: {{ index .Values.resources.limits "ephemeral-storage" }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LABELS_FILE
          value: /etc/podinfo/labels
        - name: VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['parrot-app-version']
        - name: MY_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: parrot-app
              divisor: "1m"
              resource: requests.cpu
        - name: MY_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: parrot-app
              divisor: "1m"
              resource: limits.cpu
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: parrot-app
              divisor: "1M"
              resource: requests.memory
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: parrot-app
              divisor: "1M"
              resource: limits.memory
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: MY_EPH_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: parrot-app
              divisor: "1M"
              resource: limits.ephemeral-storage
        - name: DEPLOYMENT_NAME
          value: {{ .Release.Name }}
        {{- if .Values.hpaBench.enabled }}
        - name: HPA_BENCH
          value: "true"
        - name: MEMCACHE_HOST
          value: "{{ .Release.Name }}-memcached:11211"
        {{- end }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: podinfo
          mountPath: /etc/podinfo
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
      - name: nginx-config
        configMap:
          name: {{ .Release.Name }}-nginx-config
