{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`)
      services:
        - name: {{ .Release.Name }}
          port: {{ .Values.service.port }}
          {{- if .Values.ingress.sticky }}
          sticky:
            cookie:
              name: parrot_sticky
              httpOnly: true
              sameSite: lax
          {{- end }}
{{- end }}
